<a href="https://colab.research.google.com/github/akshadjaiswal005/Machine-Learning-TAE1-Group8/blob/main/Final_Heart_Disease_All_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CS23059 Tisha Mondal

# Heart Disease Prediction - Final Model Comparison

This notebook implements and compares six machine learning models on the UCI Heart Disease dataset.
Each model is evaluated using two different train-test splits (80:20 and 70:30).

Models Used:
- Decision Tree
- Support Vector Machine (SVM)
- Naive Bayes
- Logistic Regression
- K-Nearest Neighbors (KNN)
- Random Forest

# Final Model Comparison - Heart Disease Prediction

This notebook combines and evaluates six machine learning models using 80:20 and 70:30 train-test splits.

In [6]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [7]:
url = "https://raw.githubusercontent.com/akshadjaiswal005/Machine-Learning-TAE1-Group8/refs/heads/main/heart_disease_uci.csv"
df = pd.read_csv(url)

df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0


In [8]:
print(df.shape)
print(df.columns)
df.info()

(920, 16)
Index(['id', 'age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs',
       'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   id        920 non-null    int64  
 1   age       920 non-null    int64  
 2   sex       920 non-null    object 
 3   dataset   920 non-null    object 
 4   cp        920 non-null    object 
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object 
 8   restecg   918 non-null    object 
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object 
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object 
 13  ca        309 non-null    float64
 14  thal      434 non-null    object 
 15  num       920 non-null    int64  
dtypes: flo

In [9]:
# Drop unnecessary column
df.drop("id", axis=1, inplace=True)

# Convert target to binary (classification)
df["num"] = df["num"].apply(lambda x: 1 if x > 0 else 0)

# Handle categorical data
df = pd.get_dummies(df, drop_first=True)

# Define features and target
X = df.drop("num", axis=1)
y = df["num"]

In [10]:
# Impute missing values (IMPORTANT for SVM)
imputer = SimpleImputer(strategy="mean")
X = imputer.fit_transform(X)

In [11]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [12]:
def evaluate_model(model, name):

    print(f"\n================ {name} ================")

    # 🔹 80:20 Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print("\n--- 80:20 Split ---")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))


    # 🔹 70:30 Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42
    )

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print("\n--- 70:30 Split ---")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))

In [13]:
evaluate_model(DecisionTreeClassifier(), "Decision Tree")
evaluate_model(SVC(), "SVM")
evaluate_model(GaussianNB(), "Naive Bayes")


================ Decision Tree ================

--- 80:20 Split ---
Accuracy: 0.7608695652173914
Confusion Matrix:
 [[57 18]
 [26 83]]
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.76      0.72        75
           1       0.82      0.76      0.79       109

    accuracy                           0.76       184
   macro avg       0.75      0.76      0.76       184
weighted avg       0.77      0.76      0.76       184


--- 70:30 Split ---
Accuracy: 0.7644927536231884
Confusion Matrix:
 [[ 89  31]
 [ 34 122]]
Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.74      0.73       120
           1       0.80      0.78      0.79       156

    accuracy                           0.76       276
   macro avg       0.76      0.76      0.76       276
weighted avg       0.77      0.76      0.76       276


================ SVM ================

--- 80:20 Split ---
Accuracy:

In [14]:
evaluate_model(LogisticRegression(max_iter=1000), "Logistic Regression")
evaluate_model(KNeighborsClassifier(), "KNN")
evaluate_model(RandomForestClassifier(), "Random Forest")


================ Logistic Regression ================

--- 80:20 Split ---
Accuracy: 0.8369565217391305
Confusion Matrix:
 [[63 12]
 [18 91]]
Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.84      0.81        75
           1       0.88      0.83      0.86       109

    accuracy                           0.84       184
   macro avg       0.83      0.84      0.83       184
weighted avg       0.84      0.84      0.84       184


--- 70:30 Split ---
Accuracy: 0.822463768115942
Confusion Matrix:
 [[ 99  21]
 [ 28 128]]
Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.82      0.80       120
           1       0.86      0.82      0.84       156

    accuracy                           0.82       276
   macro avg       0.82      0.82      0.82       276
weighted avg       0.82      0.82      0.82       276


================ KNN ================

--- 80:20 Split ---
Accu

## Conclusion

In this project, six machine learning models were implemented and evaluated on the UCI Heart Disease dataset.

Each model was tested using two different train-test splits (80:20 and 70:30) to analyze performance under varying training data sizes.

The results show that ensemble models like Random Forest and algorithms like SVM generally provide higher accuracy, while simpler models like Naive Bayes are faster but may have slightly lower performance.

This comparative analysis helps in selecting the most suitable model for heart disease prediction based on accuracy and efficiency.